name: Build and Deploy
env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.token }} # This is automatically set by Github Actions
  USE_GITHUB_DATA: "true"
  MEDIUM_USERNAME: "@guvalaprashanth342" # Change this to your medium username
on:
  workflow_dispatch:
  push:
    branches:
      - test
  schedule:
    - cron: "0 12 * * 1" # see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3 # If you're using actions/checkout@v3 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Node.js ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Update npm ğŸš€
        run: npm install -g npm@latest
      
      - name: Debug environment variables
        run: printenv | grep REACT_APP_GITHUB_TOKEN
      

      - name: Install and Build ğŸ”§ # Build the Project
        env: 
          REACT_APP_GITHUB_TOKEN: ${{secrets.token}}
        run: |
          npm install
          npm run build
          printenv | grep REACT_APP_GITHUB_TOKEN
          cat ./build/profile.json
          cat ./build/blogs.json
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token : ${{ secrets.GITHUB_TOKEN }} # This is provided by GitHub.
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
